typography_spectrum: 0.94696
color:
  saturation: 0.5625
  brandStrength: 0.8125
  rhythmicContrast: 0.75
  brandColors:
    - '#02070b'
    - '#09364b'
    - '#58726f'
    - '#788d86'
    - '#96aba4'
  lightness: 0.375
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4450418
analytics:
  twitter: null
  google: null
  facebook: null
name: High Hopes & Hard Dreams
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    id: 949211f9-54fe-481f-ad5e-65a73f6c7013
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: High Hopes & Hard Dreams
purpose: []
