name: highhopesharddreams
favicon: null
layout_spectrum: 0.4906002401839942
typography_spectrum: 0.6198180494830012
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9616828744765371
  lightness: 0.7673002805095166
  saturation: 0.9255636688321829
  rhythmicContrast: 0.8323625086341053
purpose: []
