name: 'High Hopes & Hard Dreams'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.57709
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'High Hopes & Hard Dreams'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02070b'
    - '#09364b'
    - '#58726f'
    - '#788d86'
    - '#96aba4'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
