name: High Hopes & Hard Dreams
favicon: null
layout_spectrum: 0.25267
typography_spectrum: 0.94696
navigation:
  - name: About
    id: 949211f9-54fe-481f-ad5e-65a73f6c7013
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: High Hopes & Hard Dreams
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02070b'
    - '#09364b'
    - '#58726f'
    - '#788d86'
    - '#96aba4'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
